version: "3"
services:
  app:
    container_name: app
    image: fabscm/stadtfuehrer-muenster
    ports:
      - "4000:3000" # forward webserver on standard-http port
    depends_on:
      - mongodbservice
  mongodbservice:
    container_name: mongo
    image: mongo # to be retrieved from dockerhub
    ports:
      - "27017:27017" # forward mongod port
    volumes:
      - ./data:/data/db 
  mongoexpressservice: 
    container_name: mongo-express-service
    image: mongo-express
    ports: 
            - '8081:8081'
    restart: always

    # find out where to mount to in the image's Dockerfile;
    #           here: https://github.com/docker-library/mongo/blob/00a8519463e776e797c227681a595986d8f9dbe1/3.0/Dockerfile